GreenHost/GreenHost/Models/Member.cs
namespace GreenHost.Models;

public class Member : BaseEntity
{
    public string Fullname { get; set; }
    public string Image { get; set; }
    public int DepartmentId { get; set; }
    public Department Department { get; set; }

}

GreenHost/GreenHost/Areas/Admin/Controllers/DepartmentController.cs
using GreenHost.Contexts;
using GreenHost.Models;
using GreenHost.ViewModels.DepartmentVMs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GreenHost.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DepartmentController : Controller
    {
        private readonly GreenHostDbContext _context;

        public DepartmentController(GreenHostDbContext context)
        {
            _context = context;     
        }

        public async Task<IActionResult> Index()
        {

            return View(await _context.Department.ToListAsync());
        }
        public async Task<IActionResult> Info(int? id) 
        {
          
            return View(await _context.Department.FindAsync(id));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _context.Department.FindAsync(id);
            if (data == null) return NotFound();
            _context.Department.Remove(data);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
      
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentCreateVM vm)
        {
            if (vm == null) throw new Exception("Can't be null");
            if (!ModelState.IsValid) return View(vm);
            Department department = new Department
            {
                Name = vm.Name
            };
            await _context.Department.AddAsync(department);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _context.Department.FindAsync(id);
            if (data == null) return NotFound();
            DepartmentUpdateVM vm = new DepartmentUpdateVM
            {
                Name = data.Name
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id, DepartmentUpdateVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var data = await _context.Department.FindAsync(id);
            if (data is not null)
            {
                data.Name = vm.Name;

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }


    }
}

GreenHost/GreenHost/Areas/Admin/Controllers/MemberController.cs
using GreenHost.Contexts;
using GreenHost.Models;
using GreenHost.ViewModels.MemberVMs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GreenHost.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MemberController : Controller
    {
        private readonly GreenHostDbContext _context;

        public MemberController(GreenHostDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _context.Members.Include(m => m.Department).ToListAsync());
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Department = await _context.Department.Where(x => !x.IsDeleted).ToListAsync();
            return View();
        }
        public async Task<IActionResult> Info(int? id) 
        {
            if (id == null) return BadRequest();
            return View(await _context.Members.Include(m => m.Department).FirstOrDefaultAsync(x => x.Id ==id));

        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _context.Members.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (data == null) return NotFound();
            _context.Members.Remove(data);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(MemberCreateVM vm)
        {
            return View();
            //        if (vm.ImageUrl != null)
            //        {
            //            if (!vm.ImageUrl.IsValidType("image"))
            //                ModelState.AddModelError("File", "File must be an image");
            //            if (!vm.ImageUrl.IsValidSize(400))
            //                ModelState.AddModelError("File", "File must be less than 400kb");
            //        }

            //        if (!ModelState.IsValid)
            //        {
            //            ViewBag.Categories = await _context.Department.Where(x => !x.IsDeleted).ToListAsync();
            //            return View(vm);
            //        }

            //        if (!await _context.Department.AnyAsync(x => x.Id == vm.DepartmentId && !x.IsDeleted))
            //        {
            //            ViewBag.Categories = await _context.Department.Where(x => !x.IsDeleted).ToListAsync();
            //            ModelState.AddModelError("DepartmentId", "Department not found or deleted");
            //            return View(vm);
            //        }

            //        var productImagePath = Path.Combine(_env.WebRootPath, "imgs", "agents");
            //        Member memb = new Member
            //        {
            //            Fullname=vm.FullName,
            //            Image=vm.Image,
            //            DepartmentId=vm.DepartmentId

            //        };
            //        if (vm.Image != null)
            //        {
            //            memb.Image = await vm.Image.UploadAsync(productImagePath);
            //        }

            //        await _context.Members.AddAsync(memb);
            //        await _context.SaveChangesAsync();
            //        return RedirectToAction("Index");
            //    }
            //    public async Task<IActionResult> Update(int? id)
            //    {
            //        if (id == null) return BadRequest();
            //        var data = await _context.Agents.Where(x => x.Id == id).Select(x => new AgentUpdateVM
            //        {
            //            FullName = x.FullName,
            //            DepartmentID = x.DepartmenId,
            //            ImageUrl = x.ImageUrl,
            //        }).FirstOrDefaultAsync();
            //        if (data == null) return NotFound();
            //        ViewBag.Department = await _context.Departments.Where(x => !x.IsDeleted).ToListAsync();
            //        return View(data);
            //    }
            //    [HttpPost]
            //    public async Task<IActionResult> Update(int? id, AgentUpdateVM vm)
            //    {
            //        if (id == null) return BadRequest();
            //        var data = await _context.Agents.Where(x => x.Id == id).FirstOrDefaultAsync();
            //        if (data == null) return NotFound();
            //        if (vm.Image is not null)
            //        {
            //            vm.Id = data.Id;
            //            vm.FullName = data.FullName;
            //            vm.DepartmentID = data.DepartmenId;
            //            vm.ImageUrl = data.ImageUrl;
            //            await _context.SaveChangesAsync();
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    public async Task<IActionResult> Delete(int? id)
            //    {
            //        if (id == null) return BadRequest();
            //        var data = await _context.Agents.Where(x => x.Id == id).FirstOrDefaultAsync();
            //        if (data == null) return NotFound();
            //        _context.Agents.Remove(data);
            //        _context.SaveChanges();
            //        return RedirectToAction("Index");
            //    }
            //}
        }
    }
}

GreenHost/GreenHost/Areas/Admin/Views/Member/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}


<form method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name">
        <span asp-validation-for="Name"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

GreenHost/GreenHost/Areas/Admin/Views/Member/Index.cshtml
@model List<Member>
@{
    ViewData["Title"] = "Index";
}


<td><a class="btn btn-primary" asp-action="Create" asp-controller="Member" class="btn btn-primary">Create</a></td>

<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Fullname</th>
                    <th>ImageUrl</th>
                    <th>Department Name</th>
                    <th>IsDeleted</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id </td>
                        <td>@item.Fullname </td>
                        <td>@item.Image </td>
                        <td>@item.Department.Name </td>
                        <td>@item.IsDeleted </td>
                        <td><a asp-action="Info" asp-controller="Member" asp-route-id="@item.Id" class="btn btn-primary">Info</a></td>
                        <td><a asp-action="Delete" asp-controller="Member" asp-route-id="@item.Id" class="btn btn-primary">Delete</a></td>
                        <td><a asp-action="Update" asp-controller="Member" asp-route-id="@item.Id" class="btn btn-primary">Update</a></td>




                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

GreenHost/GreenHost/Areas/Admin/Views/Member/Info.cshtml
@model Member

<td><a asp-action="Index" asp-controller="Department" class="btn btn-primary">Back</a></td>

<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Fullname</th>
                    <th>Image</th>
                    <th>IsDeleted</th>

                </tr>
            </thead>

            <tbody>

                <tr>
                    <td>@Model.Id </td>
                    <td>@Model.Fullname </td>
                    <td>@Model.Image </td>
                    <td>@Model.IsDeleted </td>
               

                </tr>


            </tbody>
        </table>
    </div>
</div>

GreenHost/GreenHost/Areas/Admin/Views/Member/Update.cshtml
@model DepartmentUpdateVM


<form method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name">
        <span asp-validation-for="Name"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>